language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6

env:
  global:
    - REPO_NAME=Authenticate
    - PLUGIN_NAME=Authenticate
    - REQUIRE=""

  matrix:
    - DB=mysql CAKE_VERSION=2.6
    - DB=mysql CAKE_VERSION=2.7

matrix:
  include:
    - php: 5.4
      env:
        - DB=mysql CAKE_VERSION=2.6 COVERALLS=1
    - php: 5.4
      env:
        - DB=mysql CAKE_VERSION=2.6 PHPCS=1

before_script:
  - git clone -b master https://github.com/FriendsOfCake/travis.git --depth 1 ../travis
  - ../travis/before_script.sh

script:
  - ../travis/script.sh

after_success:
  - ../travis/after_success.sh

notifications:
  email: false
