language: php

php:
  - 5.3
  - 5.4
  - 5.5

env:
  global:
    - REPO_NAME=Authenticate
    - PLUGIN_NAME=Authenticate
  matrix:
    - CAKE_VERSION=master DB=mysql
    - CAKE_VERSION=master DB=pgsql
    - CAKE_VERSION=2.5 DB=mysql
    - CAKE_VERSION=2.5 DB=pgsql

matrix:
  include:
    - php: 5.4
      env:
        - DB=mysql CAKE_VERSION=master COVERALLS=1
    - php: 5.4
      env:
        - DB=mysql CAKE_VERSION=master PHPCS=1

before_script:
  - ./travis.sh
  - cd ../cakephp

script:
  - ./lib/Cake/Console/cake test $PLUGIN_NAME All$PLUGIN_NAME --stderr --coverage-clover build/logs/clover.xml

after_success:
  - sh -c "if [ '$COVERALLS' = '1' ]; then php vendor/bin/coveralls -c .coveralls.yml -v; fi"

notifications:
  email: false
